import Head from 'next/head'
import Menu from '@/components/Menu'
import Image from 'next/image'
import Button from '@/components/Button'
import {LinkIcon, TrashIcon} from '@heroicons/react/24/solid'
import Link from 'next/link'

export default function CreateVote() {
    return (
        <div className='container mx-auto '>
            <Head>
                <title>Jujurly | Voting Baru</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Menu />
            {/* <Header> */}
            <div className='flex flex-col place-items-left py-12 space-y-4 px-20'>
                <Image
                    className='mb-3'
                    src={'/assets/vote-img.svg'}
                    width={'284'}
                    height={'198'}
                    alt={'vote-img'}></Image>
                <h1 className='text-4xl mb-2 font-bold '>Buat Voting Baru</h1>
                <h2>Silakan masukkan data yang dibutuhkan sebelum membuat vote online</h2>
                <form>
                    {/* <DetailVote> */}
                    <div>
                        <h3>Detail Voting</h3>
                        <div>
                            <label>Judul</label>
                        </div>
                    </div>
                    {/* </DetailVote> */}
                </form>
            </div>
            {/* </Header> */}
            <main className='px-20'></main>
            {/* <Footer/> */}
            <div className='px-5'>
                <footer className='bg-white rounded-lg dark:bg-gray-900 m-4'>
                    <div className='w-full container mx-auto p-4 md:px-6 '>
                        <hr className='my-6 border-gray-200 sm:mx-auto dark:border-gray-700 ' />
                        <div className='sm:flex sm:items-center sm:justify-between lg:mb-8'>
                            <Link href={'/'} className='flex items-center mb-4 sm:mb-0'>
                                <Image
                                    src={'/assets/jujurly.svg'}
                                    width={'100'}
                                    height={'100'}
                                    alt={'logo-img'}></Image>
                            </Link>
                            <ul className='flex flex-wrap items-center mb-6 text-sm font-medium text-black-500 sm:mb-0 dark:text-gray-400'>
                                <li>
                                    <Link
                                        href={'/vote/create'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        Buat Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'#'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6'>
                                        Ikut Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'#'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        GitHub Repos
                                    </Link>
                                </li>
                            </ul>
                        </div>

                        <span className='block text-sm text-gray-500 sm:text-center dark:text-gray-400'>
                            © 2023{' '}
                            <Link href={'#'} className='hover:underline'>
                                Jujurly™
                            </Link>
                            . All Rights Reserved.
                        </span>
                    </div>
                </footer>
            </div>
            {/* <Footer/> */}
        </div>
    )
}
