import Head from 'next/head'
import Menu from '@/components/Menu'
import Image from 'next/image'
import Button from '@/components/Button'
import {LinkIcon, TrashIcon} from '@heroicons/react/24/solid'
import Link from 'next/link'
import Form from '@/components/Form'
import ReactDatePicker, {registerLocale} from 'react-datepicker'
import 'react-datepicker/dist/react-datepicker.css'
import id from 'date-fns/locale/id'
import {useState} from 'react'

registerLocale('id', id)

export default function CreateVote() {
    const [startDate, setStartDate] = useState(new Date())
    const [endDate, setEndDate] = useState(new Date())
    return (
        <div className='container mx-auto '>
            <Head>
                <title>Jujurly | Voting Baru</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Menu />
            {/* <Header> */}
            <div className='flex flex-col place-items-left py-12 space-y-4 px-20'>
                <Image
                    className='mb-3'
                    src={'/assets/vote-img.svg'}
                    width={'284'}
                    height={'198'}
                    alt={'vote-img'}></Image>
                <h1 className='text-4xl mb-2 font-bold '>Buat Voting Baru</h1>
                <h2>Silakan masukkan data yang dibutuhkan sebelum membuat vote online</h2>
                <form className='flex flex-col'>
                    {/* <DetailVote> */}
                    <div className='space-y-1'>
                        <h3 className='font-medium text-xl mt-5'>Detail Voting</h3>
                        <div className='flex flex-col space-y-2'>
                            <label className='text-sm mt-5 font-bold'>Judul</label>
                            <Form
                                onChange={() => {}}
                                value={''}
                                placeHolder={'Contoh : Voting Calon Gubernur'}
                                className={'mt-1'}
                            />
                        </div>

                        <div className='flex flex-col space-y-2 mr-1'>
                            <label className='text-sm mt-5 font-bold'>Kapan dimulai?</label>
                            <div className='flex flex-row justify-between space-x-5'>
                                {/* @ts-ignore */}
                                <ReactDatePicker
                                    locale={'id'}
                                    showTimeSelect
                                    selected={startDate}
                                    onChange={date => date && setStartDate(date)}
                                    dateFormat={'Pp'}
                                    minDate={new Date()}
                                    className={'mt-1 w-full bg-zinc-100 py-2 px-3'}
                                />
                                <p className='text-sm font-bold text-center py-3 w-auto'>sampai</p>
                                {/* @ts-ignore */}
                                <ReactDatePicker
                                    locale={'id'}
                                    showTimeSelect
                                    selected={startDate}
                                    onChange={date => date && setEndDate(date)}
                                    dateFormat={'Pp'}
                                    minDate={startDate}
                                    className={'mt-1 w-full bg-zinc-100 py-2 px-3'}
                                />
                            </div>
                        </div>
                    </div>
                    {/* </DetailVote> */}
                </form>
            </div>
            {/* </Header> */}
            <main className='px-20'></main>
            {/* <Footer/> */}
            <div className='px-5'>
                <footer className='bg-white rounded-lg dark:bg-gray-900 m-4'>
                    <div className='w-full container mx-auto p-4 md:px-6 '>
                        <hr className='my-6 border-gray-200 sm:mx-auto dark:border-gray-700 ' />
                        <div className='sm:flex sm:items-center sm:justify-between lg:mb-8'>
                            <Link href={'/'} className='flex items-center mb-4 sm:mb-0'>
                                <Image
                                    src={'/assets/jujurly.svg'}
                                    width={'100'}
                                    height={'100'}
                                    alt={'logo-img'}></Image>
                            </Link>
                            <ul className='flex flex-wrap items-center mb-6 text-sm font-medium text-black-500 sm:mb-0 dark:text-gray-400'>
                                <li>
                                    <Link
                                        href={'/vote/create'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        Buat Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'#'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6'>
                                        Ikut Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'#'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        GitHub Repos
                                    </Link>
                                </li>
                            </ul>
                        </div>

                        <span className='block text-sm text-gray-500 sm:text-center dark:text-gray-400'>
                            © 2023{' '}
                            <Link href={'#'} className='hover:underline'>
                                Jujurly™
                            </Link>
                            . All Rights Reserved.
                        </span>
                    </div>
                </footer>
            </div>
            {/* <Footer/> */}
        </div>
    )
}
