import Head from 'next/head'
import {Inter} from 'next/font/google'
import Menu from '@/components/Menu'
import Image from 'next/image'
import Button from '@/components/Button'
import {LinkIcon, TrashIcon} from '@heroicons/react/24/solid'
import Link from 'next/link'
const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <div className='container mx-auto '>
            <Head>
                <title>Jujurly Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Menu />
            {/* <Header> */}
            <div className='flex flex-col place-items-center py-20 space-y-3 px-20'>
                <h1 className='text-5xl mb-2 font-bold'>Ayo Mulai Voting</h1>
                <h2 className='text-md bg-zinc-100 px-3 py-1 rounded-md'>
                    Web App Voting <span className='font-bold'>No.1</span> di Indonesia
                </h2>
                <Image
                    src={'/assets/header.svg'}
                    width={'274'}
                    style={{marginTop: '30px', marginBottom: '30px'}}
                    height={'243'}
                    alt={'header-img'}></Image>
                <div className='space-x-10 '>
                    <Button
                        url={'/vote/create'}
                        text={'Buat Voting Baru'}
                        nameClass={'font-bold'}
                        width={'w-[160px]'}
                        fontSize={'14px'}
                    />
                    <Button
                        text={'Ikut Voting'}
                        type={'secondary'}
                        nameClass={'font-bold'}
                        width={'w-[160px]'}
                        fontSize={'14px'}
                    />
                </div>
            </div>
            {/* </Header> */}
            {/* <Table> */}
            <div className='px-20'>
                <p className='py-5 text-lg font-bold'>Daftar Vote Terbuat</p>
                <table className='table-auto w-full border border-zinc-100'>
                    <thead>
                        <tr className='border-b border-zinc-100'>
                            <th className='p-5 text-center'>No</th>
                            <th className='p-5 text-center'>Judul</th>
                            <th className='p-5 text-center'>Kandidat</th>
                            <th className='p-5 text-center'>Kode</th>
                            <th className='p-5 text-center'>No</th>
                            <th className='p-5 text-center'>Selesai</th>
                            <th className='p-5 text-center'></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td className='p-5 text-center'>1</td>
                            <td className='p-5 text-center'>Judul Voting</td>
                            <td className='p-5 text-center'>Budi vs Anto</td>
                            <td className='p-5 text-center'>BXAZIRH</td>
                            <td className='p-5 text-center'>20 Oct 2022 11:00 AM</td>
                            <td className='p-5 text-center'>22 Oct 2022 11:00 AM</td>
                            <td className='p-5 text-center'>
                                <div>
                                    <Link href={'#'}>
                                        <LinkIcon className='w-8 h-8 p-2 hover:text-blue-600' />
                                    </Link>
                                </div>
                                <div>
                                    <Link href={'#'}>
                                        <TrashIcon className='w-8 h-8 p-2 hover:text-red-600' />
                                    </Link>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            {/* </Table> */}
            <main className='px-20'></main>
            {/* <Footer/> */}
            <div className='px-5'>
                <footer className='bg-white rounded-lg dark:bg-gray-900 m-4'>
                    <div className='w-full container mx-auto p-4 md:px-6 '>
                        <hr className='my-6 border-gray-200 sm:mx-auto dark:border-gray-700 ' />
                        <div className='sm:flex sm:items-center sm:justify-between lg:mb-8'>
                            <Link href={'/'} className='flex items-center mb-4 sm:mb-0'>
                                <Image
                                    src={'/assets/jujurly.svg'}
                                    width={'100'}
                                    height={'100'}
                                    alt={'logo-img'}></Image>
                            </Link>
                            <ul className='flex flex-wrap items-center mb-6 text-sm font-medium text-black-500 sm:mb-0 dark:text-gray-400'>
                                <li>
                                    <Link
                                        href={'/vote/create'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        Buat Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'#'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6'>
                                        Ikut Voting
                                    </Link>
                                </li>
                                <li>
                                    <Link
                                        href={'/'}
                                        className='mr-4 hover:underline hover:text-gray-600 md:mr-6 '>
                                        GitHub Repos
                                    </Link>
                                </li>
                            </ul>
                        </div>

                        <span className='block text-sm text-gray-500 sm:text-center dark:text-gray-400'>
                            © 2023{' '}
                            <Link href={'#'} className='hover:underline'>
                                Jujurly™
                            </Link>
                            . All Rights Reserved.
                        </span>
                    </div>
                </footer>
            </div>
            {/* <Footer/> */}
        </div>
    )
}
