import Head from 'next/head'
import {Inter} from 'next/font/google'
import Menu from '@/components/Menu'
const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <div className='container mx-auto'>
            <Head>
                <title>Jujurly Next App</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Menu />
            <main></main>
        </div>
    )
}
